using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Net;
using System.IO;
using System.Net.Mail;
using System.Diagnostics;


namespace CodeDescriptor
{

    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            this.Text = "CodeDescriptor Ver.: " + Application.ProductVersion;
        }

        private void Form1_FormClosed(object sender, FormClosedEventArgs e)
        {
            MessageBox.Show("Thank you for using!", ("CodeDescriptor " + Application.ProductVersion), MessageBoxButtons.OK, MessageBoxIcon.Information);
        }

        private void plToolStripMenuItem_Click(object sender, EventArgs e)
        {
            string Message = "mailto:J.Homann@jh-elec.de?subject= CodeDescriptor " + Application.ProductVersion;
            Process.Start(Message);
        }

        private void btn_create_Click(object sender, EventArgs e)
        {
            if ( txtbx_name_of_header.Text == "" )
            {
                MessageBox.Show("Bitte Namen der Datei angeben!");
                return;
            }


            if ( File.Exists( AppDomain.CurrentDomain.BaseDirectory + "\\" + txtbx_name_of_header.Text + ".h"))
            {
                File.Delete(AppDomain.CurrentDomain.BaseDirectory + "\\" + txtbx_name_of_header.Text + ".h");
            }

            using (StreamWriter write = new StreamWriter(AppDomain.CurrentDomain.BaseDirectory + "\\" + txtbx_name_of_header.Text + ".h", true))
            {
                string Header =

                "/* Generated by " + Application.ProductName + " " + Application.ProductVersion + " */" + "\r\n" +
                "/*" + "\r\n" +
                "* Project Name -> " + txtbx_name_of_header.Text +  "\r\n" +
                "* Version      -> " + numeric_major.Value.ToString() + "." + numeric_minor.Value.ToString() + "." + DateTime.Now.ToString("HHmm.ddMM") + "\r\n" +
                "* Author       -> " + Environment.UserName      +  "\r\n" +
                "* Build Date   -> " + DateTime.Now.ToString("HH:mm:ss - dd.MM.yyyy") + "\r\n" +
                "* Description  -> " +
                "*" + "\r\n" +
                "*" + "\r\n" +
                "*" + "\r\n" +
                "*/";

                write.WriteLine(Header);
            }
        }
    }
}



